### PR TITLE
Update interfaces.cpp

### PR DESCRIPTION
**Pull request by bruhmoment21**

### CODE REVIEW

**Comment by designer1337** [comment]
whats the point of this?

**Comment by bruhmoment21** [comment]
first one crashing for me

**Comment by designer1337** [comment]
ill try this rn, it should be fine like this

**Comment by designer1337** [comment]
i dont remember any game updates, but yeah seems like this is outdated

**Comment by behality** [comment]
New one is crashing, but old is working fine to me

**Comment by designer1337** [comment]
> New one is crashing, but old is working fine to me

It's crashing only with new beta, if u are using stable build use old indexes

**Comment by behality** [comment]
> > New one is crashing, but old is working fine to me
> 
> It's crashing only with new beta, if u are using stable build use old indexes

Ohok

**Pull request merged**
