### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by bruhmoment21**

### CODE REVIEW

**Comment by behality** [comment]
Fix compile errors: https://ci.appveyor.com/project/designer1337/csgo-cheat-base/builds/33938661

**Comment by bruhmoment21** [comment]
fuck now i have to see my mistake ill make one tommorow

**Comment by behality** [comment]
Also, why float for screen size:
`int x, y;`
`interfaces::engine->get_screen_size( x, y );`

`screen.x = static_cast<float>(x) / 2.0f;`
`screen.y = static_cast<float>(y) / 2.0f;`

**Comment by bruhmoment21** [comment]
there are no compile errors lmao

**Comment by behality** [comment]
> there are no compile errors lmao
I rebuilt the solution now, there really are no compiler errors, sorry. gj

**Pull request merged**
